# Generated by Django 5.2.7 on 2025-11-07 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PhotoMetadata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('photographer', models.CharField(max_length=200)),
                ('date_taken', models.DateField()),
                ('url', models.URLField()),
                ('description', models.TextField()),
                ('location', models.CharField(max_length=200)),
                ('tags', models.TextField(blank=True)),
                ('width', models.PositiveIntegerField()),
                ('height', models.PositiveIntegerField()),
                ('camera', models.CharField(max_length=200)),
                ('license', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
