# Dockerfile
FROM python:3.13

# переменные окружения
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

# рабочая папка
WORKDIR /app

# системные зависимости для Pillow, psycopg2 и т.д.
RUN apt-get update && apt-get install -y --no-install-recommends \
    build-essential \
    libpq-dev \
    gcc \
    libjpeg-dev \
    zlib1g-dev \
    gettext \
 && rm -rf /var/lib/apt/lists/*

# скопировать только зависимости сначала (кэширование слоёв)
COPY requirements.txt /app/

RUN pip install --upgrade pip
RUN pip install -r /app/requirements.txt

# скопировать проект
COPY . /app

# сделать исполняемым entrypoint
COPY ./docker/entrypoint.sh /app/docker-entrypoint.sh
RUN chmod +x /app/docker-entrypoint.sh

# Создаём пользователя (не root)
RUN useradd -m webuser
USER webuser

EXPOSE 8000

ENTRYPOINT ["/app/docker-entrypoint.sh"]
CMD ["gunicorn", "photoweb_project.wsgi:application", "--bind", "0.0.0.0:8000", "--workers", "3"]
